"""Embedded ICC profiles matching the preview's display-encoded levels.

RGB: Qt QColorSpace(SRgb).iccProfile(), D65/sRGB primaries and sRGB transfer.
Gray: LittleCMS cmsCreateGrayProfile(D65 xyY=(.3127,.3290,1), sRGB rTRC),
with the curve read from cmsCreate_sRGBProfile and a fixed creation date.
These viewing conventions do not calibrate the camera or alter stored samples.
Embedding the small profiles avoids Qt/LCMS imports and external files at export.
"""
import base64

SRGB = base64.b64decode(
    'AAAB4AAAAAAEQAAAbW50clJHQiBYWVogAAAAAAAAAAAAAAAAYWNzcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAPbWAAEAAAAA0y1RdAYLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK'
    'clhZWgAAAPwAAAAUZ1hZWgAAARAAAAAUYlhZWgAAASQAAAAUd3RwdAAAATgAAAAUY3BydAAAAUwAAAAiY2hhZAAA'
    'AXAAAAAsclRSQwAAAZwAAAAgZ1RSQwAAAZwAAAAgYlRSQwAAAZwAAAAgZGVzYwAAAbwAAAAkWFlaIAAAAAAAAG+f'
    'AAA49AAAA5FYWVogAAAAAAAAYpYAALeHAAAY3FhZWiAAAAAAAAAkoQAAD4UAALbTWFlaIAAAAAAAAPNPAAEAAAAB'
    'FsJtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAAYAAAAcAE4ALwBBAABzZjMyAAAAAAABDEAAAAXd///zKgAAB5IAAP2P'
    '///7ov///aMAAAPaAADAh3BhcmEAAAAAAAMAAAACZmYAAPKnAAANWQAAE9AAAApbbWx1YwAAAAAAAAABAAAADGVu'
    'VVMAAAAIAAAAHABzAFIARwBC'
)

SRGB_GRAY = base64.b64decode(
    'AAABbGxjbXMEQAAAbW50ckdSQVlYWVogB+oACQAKAAAAAAAAYWNzcEFQUEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAPbWAAEAAAAA0y1sY21zAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE'
    'ZGVzYwAAALQAAAA2Y3BydAAAAOwAAABMd3RwdAAAATgAAAAUa1RSQwAAAUwAAAAgbWx1YwAAAAAAAAABAAAADGVu'
    'VVMAAAAaAAAAHABnAHIAYQB5ACAAYgB1AGkAbAB0AC0AaQBuAABtbHVjAAAAAAAAAAEAAAAMZW5VUwAAADAAAAAc'
    'AE4AbwAgAGMAbwBwAHkAcgBpAGcAaAB0ACwAIAB1AHMAZQAgAGYAcgBlAGUAbAB5WFlaIAAAAAAAAPNRAAEAAAAB'
    'FsxwYXJhAAAAAAADAAAAAmZmAADypwAADVkAABPQAAAKWw=='
)
