"""Embedded ICC profiles for linear float TIFF interoperability.

RGB: Qt QColorSpace(SRgbLinear).iccProfile(), D65/sRGB primaries, gamma 1.
Gray: LittleCMS cmsCreateGrayProfile(D65 xyY=(.3127,.3290,1), cmsBuildGamma(1)).
These generated profiles mark linear transfer; they do not calibrate the camera.
Embedding the small profiles avoids Qt/LCMS imports and external files at export.
"""
import base64

LINEAR_SRGB = base64.b64decode(
    'AAAB3AAAAAAEQAAAbW50clJHQiBYWVogAAAAAAAAAAAAAAAAYWNzcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAPbWAAEAAAAA0y1RdAYLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK'
    'clhZWgAAAPwAAAAUZ1hZWgAAARAAAAAUYlhZWgAAASQAAAAUd3RwdAAAATgAAAAUY3BydAAAAUwAAAAiY2hhZAAA'
    'AXAAAAAsclRSQwAAAZwAAAAMZ1RSQwAAAZwAAAAMYlRSQwAAAZwAAAAMZGVzYwAAAagAAAAyWFlaIAAAAAAAAG+f'
    'AAA49AAAA5FYWVogAAAAAAAAYpYAALeHAAAY3FhZWiAAAAAAAAAkoQAAD4UAALbTWFlaIAAAAAAAAPNPAAEAAAAB'
    'FsJtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAAYAAAAcAE4ALwBBAABzZjMyAAAAAAABDEAAAAXd///zKgAAB5IAAP2P'
    '///7ov///aMAAAPaAADAh2N1cnYAAAAAAAAAAG1sdWMAAAAAAAAAAQAAAAxlblVTAAAAFgAAABwATABpAG4AZQBh'
    'AHIAIABzAFIARwBCAAA='
)

LINEAR_GRAY = base64.b64decode(
    'AAABXGxjbXMEQAAAbW50ckdSQVlYWVogB+oACQALAAAAAAAAYWNzcEFQUEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAPbWAAEAAAAA0y1sY21zAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE'
    'ZGVzYwAAALQAAAA2Y3BydAAAAOwAAABMd3RwdAAAATgAAAAUa1RSQwAAAUwAAAAQbWx1YwAAAAAAAAABAAAADGVu'
    'VVMAAAAaAAAAHABnAHIAYQB5ACAAYgB1AGkAbAB0AC0AaQBuAABtbHVjAAAAAAAAAAEAAAAMZW5VUwAAADAAAAAc'
    'AE4AbwAgAGMAbwBwAHkAcgBpAGcAaAB0ACwAIAB1AHMAZQAgAGYAcgBlAGUAbAB5WFlaIAAAAAAAAPNRAAEAAAAB'
    'FsxwYXJhAAAAAAAAAAAAAQAA'
)
