"""Hover help for capture configuration, expressed in the GUI's displayed units."""

CONTROL_HELP = {
    'stack_percent': 'Stack this percentage of frames surviving cached quality/shape screening, ranked from sharpest to softest. Lower percentages can reduce seeing blur but increase noise. Run Preprocess first. Changing this value reuses the measurements and affects the next run; 100 uses all screened frames. Ignored when cached preprocessing is disabled.',
    'frame_preselection': 'Use matching cached quality and shape decisions for this run. The separate Preprocess button creates or refreshes measurements and geometry estimates. Turning this off keeps all frames except existing validity, saturation and registration rejections.',
    'device': 'Choose CPU or CUDA GPU processing. Auto uses a supported GPU when available. Geometry processing uses CPU.',
    'threads': 'Maximum CPU worker threads for the next run, from 1 to 32.',
    'batch_frames': 'Number of frames read per batch. Larger batches use more memory; progress and checkpoints update after each batch.',
    'max_ram_bytes': 'Optional Linux process memory limit in MiB, including mapped libraries. Leave blank for the default memory policy.',
    'max_vram_bytes': 'Optional CUDA tensor memory budget in MiB. Driver and external library memory are additional. Leave blank for the default policy.',
    'crop': 'Select the feature or bland observed crop when opening a simulation HDF5 capture.',
    'bayer_override': 'Use the capture header, force monochrome, or select the sensor Bayer pattern. Bayer captures reconstruct as RGB.',
    'endian_override': 'Force little-endian or big-endian sample decoding when the capture header describes the byte order incorrectly.',
    'endian_convention': 'Interpret the SER byte-order flag using the common ecosystem convention or the written SER specification.',
    'recover_complete_frames': 'Recover complete frames from a truncated SER capture. Incomplete frame data is discarded.',
    'reject_saturated': 'Reject frames with more than 5% of samples at the detector ceiling, or any sample at an explicitly set saturation threshold.',
    'reference_index': 'Frame used as the alignment reference, numbered from zero. Zero selects the highest-quality retained frame when cached preprocessing is enabled, otherwise the first usable frame. A nonzero value selects that frame explicitly.',
    'max_shift_px': 'Reject a frame if its estimated translation exceeds this distance in either axis, in pixels.',
    'cadence_s': 'Time between frame starts in seconds. Leave blank to use available capture timestamps.',
    'exposure_s': 'Exposure duration per frame in seconds. Geometry uses the exposure midpoint and checks motion during the exposure.',
    'bias_path': 'Optional bias NPY table to subtract from each raw frame. It must match the detector frame shape. Clear the path to disable it.',
    'dark_path': 'Optional dark NPY table to subtract after bias correction. It must already be scaled to the capture exposure. Clear the path to disable it.',
    'flat_path': 'Optional positive flat-field NPY table to correct pixel sensitivity. It must match the detector frame shape. Clear the path to disable it.',
    'gain_e_per_adu': 'Electrons per ADU for converting calibrated samples to electrons. Leave blank to retain the input intensity units.',
    'read_noise_e': 'Optional read noise in electrons, recorded as calibration metadata. This does not denoise the stack.',
    'saturate_adu': 'Optional raw-sample saturation threshold in ADU. With saturated-frame rejection enabled, any sample reaching it rejects that frame.',
    'geometry_mode': 'Choose translation only (none), field rotation, globe surface rotation, both (combined), or the Saturn globe-and-ring model.',
    'reference_epoch_s': 'Time of the reconstructed output view, in seconds from the capture start.',
    'field_angle0_rad': 'Field orientation at the output epoch, in degrees.',
    'field_rate_rad_s': 'Field rotation rate in degrees per second. Leave blank to estimate it from the capture when geometry requires it.',
    'surface_rate_rad_s': 'Rigid globe rotation rate in degrees per second. Preprocess fills this only when motion is reliably measured. Blank applies no surface rotation; surface mode still aligns frame translation.',
    'field_center_x': 'Horizontal rotation centre in pixels, increasing to the right. Leave blank to estimate the centre.',
    'field_center_y': 'Vertical rotation centre in pixels, increasing downwards. Leave blank to estimate the centre.',
    'equatorial_radius_px': 'Globe equatorial radius in pixels for the geometry model.',
    'flattening': 'Globe flattening: 1 minus polar radius divided by equatorial radius. Zero is spherical. Preprocessing estimates it from retained silhouettes, conditional on viewing latitude and a full globe outline.',
    'pole_pa_rad': 'Projected orientation of the globe rotation pole, in degrees.',
    'sub_obs_lat_rad': 'Signed latitude facing the observer, in degrees. The sign selects which pole is tilted towards the observer.',
    'sub_obs_lon0_rad': 'Globe longitude facing the observer at the output epoch, in degrees.',
    'ring_inner_radius_px': 'Inner radius of the Saturn ring annulus in pixels, measured in the ring plane.',
    'ring_outer_radius_px': 'Outer radius of the Saturn ring annulus in pixels, measured in the ring plane.',
    'ring_transmission': 'Fraction of globe light transmitted through the rings: 0 is opaque and 1 is fully transparent.',
    'sun_lon_rad': 'Sun longitude in the Saturn model, in degrees. Set with Sun latitude to model illumination and shadows.',
    'sun_lat_rad': 'Sun latitude in the Saturn model, in degrees. Set with Sun longitude to model illumination and shadows.',
    'moon_x': 'Horizontal moon-mask centre at the output epoch, in pixels. Set with moon y and radius.',
    'moon_y': 'Vertical moon-mask centre at the output epoch, in pixels. Set with moon x and radius.',
    'moon_radius_px': 'Radius in pixels of the moon mask excluded from the Saturn reconstruction.',
    'moon_vx_px_s': 'Horizontal moon-mask velocity in pixels per second, positive to the right.',
    'moon_vy_px_s': 'Vertical moon-mask velocity in pixels per second, positive downwards.',
}
