"""Hover help for capture configuration, expressed in the GUI's displayed units."""

CONTROL_HELP = {
    'local_patch_size': 'Width and height of each local alignment patch in detector pixels. Enter an odd size from 15 to 255; default 65. Smaller patches follow finer distortions but need stronger texture; larger patches combine more detail and may average over local motion. Spacing is half the size, rounded down. Applied on the next run without repeating preprocessing. This is manual sizing, not an automatic estimate.',
    'frame_selection_mode': 'Optional selection for comparison: Quality range keeps scores above a cutoff between the capture worst and best; Frame count keeps a ranked percentage of screened frames. 100% uses all screened frames in either mode. The aim remains improved reconstruction from more frames.',
    'squared_quality_weights': 'Optional stronger preference for sharper frames: square the cached quality score used for stacking. Retains every selected frame, the reference and alignment, and adds no sharpening. Requires Local patch alignment and cached preprocessing with Motion model none. Experimental: may trade higher noise for less seeing blur; linear weighting remains the default. Changes apply to the next fresh run.',
    'local_alignment': 'Default local seeing correction using overlapping texture patches and an averaged reference anchored to the best selected frame. Uses all colours for Bayer registration while keeping cached quality weights and original colour samples. Keeps the same selected frames and adds no sharpening. Requires cached preprocessing and Motion model none; weak or ambiguous patches keep global alignment. Enabled by default for new runs; processing is slower than global alignment.',
    'stack_percent': 'Default upper quality range is 50%; choose 100 to use all screened frames. Quality range: 50 keeps scores strictly above (best + worst) / 2, then applies screening. Other percentages keep the upper part of that range. Frame count: keeps this percentage of screened frames ranked by quality. Lower values trade noise for less seeing blur. Run Preprocess first; changes reuse measurements on the next run. Ignored when cached preprocessing is disabled.',
    'frame_preselection': 'Use matching cached quality and shape decisions for this run. The separate Preprocess button creates or refreshes measurements and geometry estimates. Turning this off keeps all frames except existing validity, saturation and registration rejections.',
    'device': 'Choose CPU or CUDA GPU processing. Auto uses a supported GPU when available. Geometry processing uses CPU.',
    'threads': 'Maximum CPU worker threads for the next run, from 1 to 32.',
    'batch_frames': 'Number of frames read per batch. Larger batches use more memory; progress and checkpoints update after each batch.',
    'max_ram_bytes': 'Optional Linux process memory limit in MiB, including mapped libraries. Leave blank for the default memory policy.',
    'max_vram_bytes': 'Optional CUDA tensor memory budget in MiB. Driver and external library memory are additional. Leave blank for the default policy.',
    'crop': 'Select the feature or bland observed crop when opening a simulation HDF5 capture.',
    'bayer_override': 'Use the capture header, force monochrome, or select the sensor Bayer pattern. Bayer captures reconstruct as RGB.',
    'endian_override': 'Force little-endian or big-endian sample decoding when the capture header describes the byte order incorrectly.',
    'endian_convention': 'Interpret the SER byte-order flag using the common ecosystem convention or the written SER specification.',
    'recover_complete_frames': 'Recover complete frames from a truncated SER capture. Incomplete frame data is discarded.',
    'reject_saturated': 'Reject frames with more than 5% of samples at the detector ceiling, or any sample at an explicitly set saturation threshold.',
    'reference_index': 'Frame used as the alignment reference, numbered from zero. Zero selects the highest-quality retained frame when cached preprocessing is enabled, otherwise the first usable frame. A nonzero value selects that frame explicitly.',
    'max_shift_px': 'Reject a frame if its estimated translation exceeds this distance in either axis, in pixels.',
    'cadence_s': 'Time between frame starts in seconds. Leave blank to use available capture timestamps.',
    'exposure_s': 'Exposure duration per frame in seconds. Blank uses recorded capture exposure when available; 0 disables the midpoint offset. A manual value overrides metadata for each new run. Geometry uses the exposure midpoint and checks motion during the exposure. Frame cadence is separate.',
    'bias_path': 'Optional bias NPY table to subtract from each raw frame. It must match the detector frame shape. Clear the path to disable it.',
    'dark_path': 'Optional dark NPY table to subtract after bias correction. It must already be scaled to the capture exposure. Clear the path to disable it.',
    'flat_path': 'Optional positive flat-field NPY table to correct pixel sensitivity. It must match the detector frame shape. Clear the path to disable it.',
    'gain_e_per_adu': 'Electrons per ADU for converting calibrated samples to electrons. Leave blank to retain the input intensity units.',
    'read_noise_e': 'Optional read noise in electrons, recorded as calibration metadata. This does not denoise the stack.',
    'saturate_adu': 'Optional raw-sample saturation threshold in ADU. With saturated-frame rejection enabled, any sample reaching it rejects that frame.',
    'geometry_mode': 'None performs ordinary stacking of any planet, including Saturn and its rings. Other modes apply field or globe motion compensation. Saturn is a separate globe-and-ring motion model requiring manually supplied signed viewing latitude and globe/ring radii; it is not a target selector.',
    'reference_epoch_s': 'Time of the reconstructed output view, in seconds from the capture start.',
    'field_angle0_rad': 'Field orientation at the output epoch, in degrees.',
    'field_rate_rad_s': 'Field rotation rate in degrees per second. Leave blank to estimate it from the capture when geometry requires it; the run stops if the estimate is unresolved. Enter 0 explicitly to disable field rotation.',
    'surface_rate_rad_s': 'Rigid globe rotation rate in degrees per second. Preprocess fills this only when motion is reliably measured. Surface, Combined and Saturn runs require a resolved rate; blank blocks the run. Enter 0 explicitly to disable spin, or choose None for ordinary stacking.',
    'field_center_x': 'Horizontal rotation centre in pixels, increasing to the right. Leave blank to estimate the centre.',
    'field_center_y': 'Vertical rotation centre in pixels, increasing downwards. Leave blank to estimate the centre.',
    'equatorial_radius_px': 'Globe equatorial radius in pixels for the geometry model.',
    'flattening': 'Globe flattening: 1 minus polar radius divided by equatorial radius. Zero is spherical. Preprocessing estimates it from retained silhouettes, conditional on viewing latitude and a full globe outline.',
    'pole_pa_rad': 'Projected orientation of the globe rotation pole, in degrees.',
    'sub_obs_lat_rad': 'Signed viewing latitude, in degrees. Its magnitude sets the ring opening and its sign selects which pole tilts towards the observer. Required for Saturn globe/ring motion compensation; the ellipse alone cannot determine the sign. Ordinary Saturn stacking uses Motion model None and does not need this value.',
    'sub_obs_lon0_rad': 'Globe longitude facing the observer at the output epoch, in degrees.',
    'ring_inner_radius_px': 'Inner radius of the Saturn ring annulus in pixels, measured in the ring plane.',
    'ring_outer_radius_px': 'Outer radius of the Saturn ring annulus in pixels, measured in the ring plane.',
    'ring_transmission': 'Fraction of globe light transmitted through the rings: 0 is opaque and 1 is fully transparent.',
    'sun_lon_rad': 'Sun longitude in the Saturn model, in degrees. Set with Sun latitude to model illumination and shadows.',
    'sun_lat_rad': 'Sun latitude in the Saturn model, in degrees. Set with Sun longitude to model illumination and shadows.',
    'moon_x': 'Horizontal moon-mask centre at the output epoch, in pixels. Set with moon y and radius.',
    'moon_y': 'Vertical moon-mask centre at the output epoch, in pixels. Set with moon x and radius.',
    'moon_radius_px': 'Radius in pixels of the moon mask excluded from the Saturn reconstruction.',
    'moon_vx_px_s': 'Horizontal moon-mask velocity in pixels per second, positive to the right.',
    'moon_vy_px_s': 'Vertical moon-mask velocity in pixels per second, positive downwards.',
}
